"""Create a playlist and add tracks to it."""
from __future__ import annotations

from collections.abc import Iterable

from .client import SpotifyClient


def create_playlist(
    client: SpotifyClient,
    name: str,
    description: str = "Generated by spotagen",
    public: bool = False,
) -> tuple[str, str]:
    """Create a playlist on the authenticated user's account.

    Returns: (playlist_id, public_url)
    """
    user_id = client.me_id()
    playlist = client.create_user_playlist(user_id, name, description, public)
    pid = str(playlist["id"])
    url = str(playlist.get("external_urls", {}).get("spotify", ""))
    return pid, url


def add_tracks(
    client: SpotifyClient, playlist_id: str, track_ids: Iterable[str]
) -> int:
    """Add tracks to a playlist in 100-id batches (Spotify's API limit).

    Returns the number of tracks added.
    """
    ids = [t for t in track_ids if t]
    uris = [f"spotify:track:{t}" for t in ids]
    for i in range(0, len(uris), 100):
        client.add_playlist_items(playlist_id, uris[i : i + 100])
    return len(uris)
